substitutions:
  name: air-conditioner
  friendly_name: "Air Conditioner"
  wifi_ap_ssid: "AC-wifi"
  wifi_ap_password: !secret wifi_ap_password
  visual_min_temperature: "17 °C"
  visual_max_temperature: "30 °C"
  visual_temperature_step: "0.5 °C"
  midea_climate_autoconf: true
  midea_climate_beeper: false

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: SMLIGHT.SLWF-01Pro
    version: "2.1"

esp8266:
  board: esp12e

wifi:
  ap:
    ssid: "${wifi_ap_ssid}"
    password: "${wifi_ap_password}"

captive_portal:

logger:
  baud_rate: 0

api:
  services:
    - service: follow_me
      variables:
        temperature: float
      then:
        midea_ac.follow_me:
          temperature: !lambda "return temperature;"
          beeper: false

ota:
  - platform: esphome

uart:
  tx_pin: 12
  rx_pin: 14
  baud_rate: 9600
  
button:
  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
  - platform: template
    name: ${friendly_name} Display Toggle
    id: midea_display_toggle
    icon: mdi:theme-light-dark
    on_press:
      midea_ac.display_toggle:
  - platform: template
    name: ${friendly_name} Swing Step
    id: midea_swing_step
    icon: mdi:tailwind
    on_press:
      midea_ac.swing_step:

climate:
  - platform: midea
    name: ${friendly_name}                            
    id: midea_climate                           
    period: 1s                                        
    timeout: 2s                                       
    num_attempts: 3                                   
    autoconf: ${midea_climate_autoconf}
    beeper: ${midea_climate_beeper}                                     
    visual:                                           
      min_temperature: "${visual_min_temperature}"    
      max_temperature: "${visual_max_temperature}"    
      temperature_step: "${visual_temperature_step}"  
    supported_modes:                                  
      - FAN_ONLY                                      
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
    custom_fan_modes:
      - SILENT
      - TURBO
    supported_presets:          
      - ECO
      - BOOST
      - SLEEP                   
    custom_presets:             
      - FREEZE_PROTECTION
    supported_swing_modes:
      - VERTICAL                
      - HORIZONTAL
      - BOTH
    outdoor_temperature:  
      name: ${friendly_name} Outdoor Temperature
    power_usage:                
      name: ${friendly_name} Power Usage
    humidity_setpoint:
      name: ${friendly_name} Indoor Humidity

switch:
  - platform: template
    name: ${friendly_name} Beeper
    id: midea_beeper
    icon: mdi:volume-source
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    turn_on_action:
      midea_ac.beeper_on:
    turn_off_action:
      midea_ac.beeper_off:

remote_transmitter:
  pin: GPIO13                       
  carrier_duty_percent: 100%

sensor:
  - platform: wifi_signal
    name: ${friendly_name} Wi-Fi Signal
    update_interval: 60s
  - platform: uptime
    name: "Uptime"
    id: uptime_sec
    internal: true
  - platform: template
    name: ${friendly_name} Uptime Days
    lambda: |-
      return (id(uptime_sec).state/60)/60/24;
    icon: mdi:clock-start
    unit_of_measurement: days
    update_interval: 60s
    
script:
  - id: on_button_click
    then:
      midea_ac.power_toggle:

web_server:
  port: 80