substitutions:
  name: air-conditioner
  friendly_name: "Air Conditioner"
  wifi_ap_ssid: "!secret air_conditioner_wifi_ap_ssid"
  wifi_ap_password: !secret air_conditioner_wifi_ap_password
  visual_min_temperature: "17 °C"
  visual_max_temperature: "30 °C"
  visual_temperature_step: "0.5 °C"
  midea_climate_autoconf: true
  midea_climate_beeper: false
  api_encryption_key: !secret api_encryption_key
  esphome_ota_password: !secret esphome_ota_password
