packages:
  - config: github://bekdan1988/slwf01pro21/yaml/config.yaml@main
    web_server: !remove
  - strings_en: github://bekdan1988/slwf01pro21/yaml/strings_en.yaml@main
  # OR FOR HUNGARIAN LANGUAGE
  # - strings_hu: github://bekdan1988/slwf01pro21/yaml/strings_hu.yaml@main
  # - wifi: github://bekdan1988/slwf01pro21/yaml/wifi.yaml@main
    # OR IF THE AC IS ON AN ANOTHER SUBNET FOR IoT DEVICES
      # ADD THE FOLLOWING LINES TO SECRETS.YAML IN ESPHOME DEVICE BUILDER
        # iot_wifi_ssid: your_iot_wifi_ssid
        # iot_wifi_password: your_iot_wifi_password
        # air-conditioner_static_ip: Air Conditioner's IP address on the IoT Subnet
        # iot_wifi_gateway: The IoT Subnet's default gateway
        # iot_wifi_subnet: The Subnet's IP address  
  - wifi_iot: github://bekdan1988/slwf01pro21/yaml/wifi_iot.yaml@main

subtitutions:
  name: air-conditioner
  friendly_name: "Air Conditioner"
  air_conditioner_wifi_ap_ssid: !secret air_conditioner_wifi_ap_ssid
  air_conditioner_wifi_ap_password: !secret air_conditioner_wifi_ap_password
  visual_min_temperature: "17 °C"
  visual_max_temperature: "30 °C"
  visual_temperature_step: "0.5 °C"
  midea_climate_autoconf: true
  midea_climate_beeper: false

#############################################
#YOU SHOULD NOT NEED TO EDIT BELOW THIS LINE#
#############################################
############################################
#A VONAL ALATTI RÉSZT NEM KELL SZERKESZTENI#
############################################

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: SMLIGHT.SLWF-01Pro
    version: "2.1"

esp8266:
  board: esp12e

captive_portal:

logger:
  baud_rate: 0

api:
  encryption:
    key: ${air_conditioner_api_encryption_key}

ota:
  - platform: esphome
    password: ${air_conditioner_ota_password}
