substitutions:
  name: legkondicionalo
  friendly_name: "Légkondícionáló"
  air_conditioner_wifi_ap_ssid: !secret air_conditioner_wifi_ap_ssid
  air_conditioner_wifi_ap_password: !secret air_conditioner_wifi_ap_password
  visual_min_temperature: "17 °C"
  visual_max_temperature: "30 °C"
  visual_temperature_step: "0.5 °C"
  midea_climate_autoconf: true
  midea_climate_beeper: false

##################################################
#A VONAL ALATTI RÉSZT NEM KELL SZERKESZTENI      #
##################################################

  air_conditioner_api_encryption_key: !secret air_conditioner_api_encryption_key
  air_conditioner_ota_password: !secret air_conditioner_ota_password
  factory_reset_button_name: Gyári visszaállítás
  display_toggle_name: Kijelző kapcsoló
  swing_step_name: Zsalumozgatás
  outdoor_temperature_name: Külső hőmérséklet
  power_usage_name: Energiafogyasztás
  humidity_setpoint_name: Beltéri páratartalom
  beeper_switch_name: Hangjelzés
  wifi_signal_sensor_name: Wi-Fi jel
  uptime_sensor_name: "Üzemidő"
  uptime_days_sensor_name: Üzemidő napban
  uptime_days_unit_of_measurement: nap

##################################################
#A VONAL ALATTI RÉSZ ISMÉT SZERKESZTHETŐ         #
##################################################

wifi:
# HASZNÁLD AZ AP MÓDOT, HA A LÉGKONDÍCIONÁLÓ UGYANAZON AZ ALHÁLÓZATON VAN, MINT A HOME ASSISTANT SZERVER
# ADD HOZZÁ AZ ALÁBBI SOROKAT A SECRETS.YAML FÁJLHOZ AZ ESPHOME DEVICE BUILDER-BEN
  # air_conditioner_wifi_ap_ssid: your_air_conditioner_wifi_ap_ssid
  # air_conditioner_wifi_ap_password: your_air_conditioner_wifi_ap_password
# VAGY HA A LÉGKONDÍCIONÁLÓ MÁSIK ALHÁLÓZATON VAN, (PL.: IoT ESZKÖZÖKNEK LEVÁLASZTOTT ALHÁLÓZAT) HASZNÁLD A MANUÁLIS IP-CÍM MÓDOT
# ADD HOZZÁ AZ ALÁBBI SOROKAT A SECRETS.YAML FÁJLHOZ AZ ESPHOME DEVICE BUILDER-BEN
  # iot_wifi_ssid: your_iot_wifi_ssid
  # iot_wifi_password: your_iot_wifi_password
  # air-conditioner_static_ip: A Légkondícionáló IP-címe AZ IoT alhálózaton
  # iot_wifi_gateway: Az IoT alhálóüzat átjárója
  # iot_wifi_subnet: Alhálózati maszk  
  
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password
  manual_ip:
    static_ip: !secret air-conditioner_static_ip
    gateway: !secret iot_wifi_gateway
    subnet: !secret iot_wifi_subnet
    ap:
      ssid: "${air_conditioner_wifi_ap_ssid}"
      password: "${air_conditioner_wifi_ap_password}"

# web_server:
  # port: 80

##################################################
#A VONAL ALATTI RÉSZT NEM KELL SZERKESZTENI      #
##################################################

climate:
  - platform: midea
    name: ${friendly_name}                            
    id: midea_climate                           
    period: 1s                                        
    timeout: 2s                                       
    num_attempts: 3                                   
    autoconf: ${midea_climate_autoconf}
    beeper: ${midea_climate_beeper}                                     
    visual:                                           
      min_temperature: "${visual_min_temperature}"    
      max_temperature: "${visual_max_temperature}"    
      temperature_step: "${visual_temperature_step}"  
    supported_modes:                                  
      - FAN_ONLY                                      
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
    custom_fan_modes:
      - SILENT
      - TURBO
    supported_presets:          
      - ECO
      - BOOST
      - SLEEP                   
    custom_presets:             
      - FREEZE_PROTECTION
    supported_swing_modes:
      - VERTICAL                
      - HORIZONTAL
      - BOTH
   
##################################################
#A VONAL ALATTI RÉSZ ISMÉT SZERKESZTHETŐ         #
##################################################
    
     # outdoor_temperature:  
      # name: ${outdoor_temperature_name}
    power_usage:                
      name: ${power_usage_name}
    # humidity_setpoint:
      # name: ${humidity_setpoint_name}

##################################################
#A VONAL ALATTI RÉSZT MÁR NEM KELL SZERKESZTENI  #
##################################################
      
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: SMLIGHT.SLWF-01Pro
    version: "2.1"

esp8266:
  board: esp12e

captive_portal:

logger:
  baud_rate: 0

api:
  encryption:
    key: ${air_conditioner_api_encryption_key}
  services:
    - service: follow_me
      variables:
        temperature: float
      then:
        midea_ac.follow_me:
          temperature: !lambda "return temperature;"
          beeper: false

ota:
  - platform: esphome
    password: ${air_conditioner_ota_password}

uart:
  tx_pin: 12
  rx_pin: 14
  baud_rate: 9600
  
button:
  - platform: factory_reset
    id: factory_reset_btn
    name: ${factory_reset_button_name}
  - platform: template
    name: ${display_toggle_name}
    id: midea_display_toggle
    icon: mdi:theme-light-dark
    on_press:
      midea_ac.display_toggle:
  - platform: template
    name: ${swing_step_name}
    id: midea_swing_step
    icon: mdi:tailwind
    on_press:
      midea_ac.swing_step:

switch:
  - platform: template
    name: ${beeper_switch_name}
    id: midea_beeper
    icon: mdi:volume-source
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    turn_on_action:
      midea_ac.beeper_on:
    turn_off_action:
      midea_ac.beeper_off:

remote_transmitter:
  pin: GPIO13                       
  carrier_duty_percent: 100%

sensor:
  - platform: wifi_signal
    name: ${wifi_signal_sensor_name}
    update_interval: 60s
  - platform: uptime
    name: "${uptime_sensor_name}"
    id: uptime_sec
    internal: true
  - platform: template
    name: ${uptime_days_sensor_name}
    lambda: |-
      return (id(uptime_sec).state/60)/60/24;
    icon: mdi:clock-start
    unit_of_measurement: ${uptime_days_unit_of_measurement}
    update_interval: 60s
    
script:
  - id: on_button_click
    then:
      midea_ac.power_toggle:
