esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: SMLIGHT.SLWF-01Pro
    version: "2.1"

esp8266:
  board: esp12e

captive_portal:

logger:
  baud_rate: 0

api:
  encryption:
    key: ${air_conditioner_api_encryption_key}
  services:
    - service: follow_me
      variables:
        temperature: float
      then:
        midea_ac.follow_me:
          temperature: !lambda "return temperature;"
          beeper: false

ota:
  - platform: esphome
    password: ${air_conditioner_ota_password}

uart:
  tx_pin: 12
  rx_pin: 14
  baud_rate: 9600
