esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: SMLIGHT.SLWF-01Pro
    version: "2.1"

esp8266:
  board: esp12e

captive_portal:

logger:
  baud_rate: 0

api:
  encryption:
    key: ${air_conditioner_api_encryption_key}

ota:
  - platform: esphome
    password: ${air_conditioner_ota_password}
