substitutions:
  lang_name: air-conditioner
  lang_friendly_name: "Air Conditioner"
  lang_air_conditioner_wifi_ap_ssid: !secret air_conditioner_wifi_ap_ssid
  lang_air_conditioner_wifi_ap_password: !secret air_conditioner_wifi_ap_password
  lang_visual_min_temperature: "17 °C"
  lang_visual_max_temperature: "30 °C"
  lang_visual_temperature_step: "0.5 °C"
  lang_midea_climate_autoconf: true
  lang_midea_climate_beeper: false
  lang_air_conditioner_api_encryption_key: !secret air_conditioner_api_encryption_key
  lang_air_conditioner_ota_password: !secret air_conditioner_ota_password
  lang_factory_reset_button_name: Factory reset
  lang_display_toggle_name: Display Toggle
  lang_swing_step_name: Swing Step
  lang_outdoor_temperature_name: Outdoor Temperature
  lang_power_usage_name: Power Usage
  lang_humidity_setpoint_name: Indoor Humidity
  lang_beeper_switch_name: Beeper
  lang_wifi_signal_sensor_name: Wi-Fi Signal
  lang_uptime_sensor_name: "Uptime"
  lang_uptime_days_sensor_name: Uptime Days
  lang_uptime_days_unit_of_measurement: days
